Feature load meshes
niivue/desktop pull request #36
Opened 2024-06-28 15:55 UTC by cdrake

# Adds new elements into the UI

- Load meshes into the UI
- Add mesh/layer management
- Option settings control
- Updates to latest version of NiiVue

2024-07-03 18:09 UTC, hanayik commented
@cdrake , I think it would be better to put all of the UI (including the tabs) inside the `<Container>` element in `App.jsx`. In the current implementation the user has to scroll the page to see the header in some cases because it sits above the `Container` in a separate box component. 

It also looks like you are not using the `<Drawer>` component anymore right, since the `Tabs` component has replaced it? If so, it would be good to remove that code if it is unused. It seems to have some icon, and I don't see those being rendered anywhere, so I assumed it was old code. 

Lastly, when clicking the hide button, the niivue canvas does not resize properly and the aspect ratio looks wrong when an image is loaded. If you update Niivue to the latest version (0.43.6), then that issue is resolved. 

Can you fix those things? After that I will bump the version and make some new releases (with macOS code signing).

2024-07-03 18:46 UTC, hanayik requested changes
I left some comments in the PR conversation area :)

2024-07-08 18:14 UTC, cdrake commented
Requested changes made

2024-07-10 19:08 UTC, hanayik approved these changes

2024-07-10 19:09 UTC, merged